#!/bin/bash

echo "// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
class Options {
  static const String amplitudeApiKey = \"$1\";
    static const String kakaoJavaScriptAppKey =
      \"$2\";
  static const String kakaoNativeAppKey = \"$3\";


}

" >> $(dirname "$0")/../lib/options.dart
