name: focus42
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  firebase_analytics: 9.3.6
  cloud_firestore: 3.4.9
  firebase_auth: 3.10.0
  firebase_core: 1.23.0
  firebase_remote_config: 2.0.18
  firebase_storage: 10.3.9
  date_format: ^2.0.6
  email_validator: ^2.0.1
  flutter_timer_countdown: ^1.0.3
  get: ^4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  logger: ^1.1.0
  url_strategy: ^0.2.0
  uuid: ^3.0.6
  webviewx: ^0.2.1
  video_player: ^2.4.5
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.7
  syncfusion_flutter_calendar: ^20.1.61
  universal_html: ^2.0.8
  flutter_svg: ^1.1.5
  flutter_riverpod: ^1.0.4
  rxdart: ^0.27.5
  jitsi_meet: ^4.0.0
  pointer_interceptor: ^0.9.3+3
  url_launcher: ^6.1.5
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/meet.png
    - assets/images/google_icon.png
    - assets/images/sorry.png
    - assets/images/default_profile.png
    - assets/images/demo.png
    - assets/images/contributor1.png
    - assets/images/contributor2.png
    - assets/images/contributor3.jpeg
    - assets/images/instagram.svg
    - assets/images/kakao.svg
    - assets/images/three_informations.svg
    - assets/images/calendarClick.gif
    - assets/images/sessionTimer.gif

    - assets/sound/ring.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSansKR-Medium.ttf
        - asset: assets/fonts/IBMPlexSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansKR-Regular.ttf
          weight: 400

    - family: Kokonor
      fonts:
        - asset: assets/fonts/Kokonor.ttf

    - family: Okddung
      fonts:
        - asset: assets/fonts/Okddung.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
